# Generated by Django 5.2.8 on 2025-11-16 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
